apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-deployment-job
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:deeebugger/ruby-config.git
    targetRevision: main
    path: environments/DEV/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-ns
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
