apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-app
    role: ingress
  name: dev-app-service
  namespace: dev-ns
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: dev-app
